version: 0.0
os: linux
files:
  - source: ./your-app-directory
    destination: /home/ubuntu/test_project
hooks:
  BeforeInstall:
    - location: scripts/before-install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/env.sh
      timeout: 300
      runas: root  
    - location: scripts/after-install.sh
      timeout: 300
      runas: root  
  ApplicationStart:
    - location: scripts/boot.sh
      timeout: 300
      runas: root
    - location: scripts/health-check.sh  # Add a health check script if needed
      timeout: 300
      runas: root
